name: Build and Publish to DockerHub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7 # O simplemente @v4 (asegúrate de que no haya una v5 disponible)

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Build and push
        uses: docker/build-push-action@v6.7.0 # v6 es la clave para Node 24
        with:
          context: .
          push: true
          tags: |
            metroveinte/gym-tracker:latest
            metroveinte/gym-tracker:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
